
import { ArchitectureLayer, Depth, Proficiency } from './types';

export const LAYERS: ArchitectureLayer[] = [
  {
    id: 'layer-1',
    title: '前端与交互层',
    englishTitle: 'Frontend & Interaction',
    color: 'purple',
    items: [
      {
        id: 'vue-react',
        name: 'Vue3 / React 核心',
        description: '熟悉 Vue3 响应式框架，能够配合主流组件库高效完成项目开发；同时了解 React 体系，具备多框架协作与迁移能力。',
        icon: 'fa-brands fa-vuejs',
        iconType: 'fa',
        proficiency: Proficiency.ADVANCED,
        depth: Depth.MEDIUM,
        colSpan: 7,
      },
      {
        id: 'api-tools',
        name: 'Axios / OpenAPI / Swagger',
        description: '熟练使用 Axios 与 Vue Router 构建单页应用，配合 Swagger/OpenAPI 标准高效完成前后端契约联调。',
        icon: 'api',
        iconType: 'material',
        proficiency: Proficiency.COMPETENT,
        depth: Depth.LOW,
        colSpan: 5,
      },
    ],
  },
  {
    id: 'layer-2',
    title: '业务与逻辑核心',
    englishTitle: 'Core Business Logic',
    color: 'amber',
    items: [
      {
        id: 'java-spring',
        name: 'Java / Spring Boot / MyBatis',
        description: '深入理解 Java 类库（如 HashMap）底层原理，熟练应用 Spring Boot 体系及 DI/IOC 概念进行独立项目开发与架构设计。',
        icon: 'fa-brands fa-java',
        iconType: 'fa',
        proficiency: Proficiency.EXPERT,
        tags: ['JAVA CORE', 'IOC/DI'],
        depth: Depth.HIGH,
        colSpan: 8,
      },
      {
        id: 'design-patterns',
        name: '设计模式与工程实践',
        description: '熟练掌握常见设计模式（单例、策略、观察者等），并能将其灵活应用于实际业务开发中，提升代码鲁棒性与可维护性。',
        icon: 'architecture',
        iconType: 'material',
        proficiency: Proficiency.ADVANCED,
        depth: Depth.MEDIUM,
        colSpan: 4,
      },
      {
        id: 'ai-coding',
        name: 'AI 辅助编程与审阅',
        description: '深度集成 Cursor, Qoder, Claude Code 等编程工具。不仅利用 AI 提效，更具备批判性审阅 AI 生成代码、确保工程质量的能力。',
        icon: 'auto_awesome',
        iconType: 'material',
        proficiency: Proficiency.ADVANCED,
        depth: Depth.MEDIUM,
        colSpan: 12,
      },
    ],
  },
  {
    id: 'layer-3',
    title: '通信与智能中间件',
    englishTitle: 'Comm & Intelligence',
    color: 'blue',
    items: [
      {
        id: 'spring-ai',
        name: 'Spring AI / LangChain4j',
        description: '熟练应用 AI 框架实现智能化改造，掌握 RAG（检索增强生成）、MCP（模型上下文协议）及 Skills/Tools 调用等前沿概念。',
        icon: 'psychology',
        iconType: 'material',
        proficiency: Proficiency.ADVANCED,
        depth: Depth.HIGH,
        colSpan: 7,
      },
      {
        id: 'netty-websocket',
        name: 'WebSocket / Netty',
        description: '熟悉实时通信技术，能够基于 Netty 框架及 Reactor 模型进行高性能应用层网络开发。',
        icon: 'lan',
        iconType: 'material',
        proficiency: Proficiency.COMPETENT,
        depth: Depth.MEDIUM,
        colSpan: 5,
      },
      {
        id: 'mq-systems',
        name: 'RabbitMQ / Kafka',
        description: '熟练掌握分布式消息队列中间件，处理异步解耦、削峰填谷等复杂分布式场景。',
        icon: 'swap_horiz',
        iconType: 'material',
        proficiency: Proficiency.ADVANCED,
        depth: Depth.MEDIUM,
        colSpan: 12,
      },
    ],
  },
  {
    id: 'layer-4',
    title: '数据与底层基座',
    englishTitle: 'Data & Infrastructure',
    color: 'cyan',
    items: [
      {
        id: 'database-sql',
        name: 'MySQL / PostgreSQL / Vector',
        description: '熟练掌握 MySQL 关系型数据库。能运用 PostgreSQL 配合插件构建向量数据库，支持 AI 应用的向量检索需求。',
        icon: 'database',
        iconType: 'material',
        proficiency: Proficiency.EXPERT,
        depth: Depth.HIGH,
        colSpan: 6,
      },
      {
        id: 'caching',
        name: 'Redis / Caffeine',
        description: '熟练应用 Redis 与 Caffeine 缓存技术，具备组织与搭建高性能多级缓存体系的实战经验。',
        icon: 'speed',
        iconType: 'material',
        proficiency: Proficiency.ADVANCED,
        depth: Depth.MEDIUM,
        colSpan: 6,
      },
      {
        id: 'docker-ops',
        name: 'Docker 容器化',
        description: '使用 Docker 进行项目容器化部署与生命周期管理，保障开发、测试、生产环境的一致性。',
        icon: 'fa-brands fa-docker',
        iconType: 'fa',
        proficiency: Proficiency.COMPETENT,
        depth: Depth.LOW,
        colSpan: 12,
      },
    ],
  },
];
