// RootLayout.tsx
import type {Metadata} from "next";
import "./globals.css";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faEnvelope, faFileAlt, faProjectDiagram} from "@fortawesome/free-solid-svg-icons";
import {faGithub} from "@fortawesome/free-brands-svg-icons"; // 从 brands 模块中导入 faGithub
import {AuroraBackground} from "@/components/ui/aurora-background";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={"antialiasing bg-black"}
        >
        <div
            className={"blog-header"}
        >
            <div
                className={"header-logo"}
            >
                <h1>JavierChen</h1>
            </div>

            <div className={"header-links"}>
                <div className={"header-links-project"}>
                    <a href={"#project"}>
                        <FontAwesomeIcon icon={faProjectDiagram} className="mr-2"/>
                        项目
                    </a>
                </div>
                <div className={"header-links-article"}>
                    <a href={"#article"}>
                        <FontAwesomeIcon icon={faFileAlt} className="mr-2"/>
                        文章
                    </a>
                </div>
            </div>

            <div className={"contact-links"}>
                <div className={"contact-links-github"}>
                    <a href={"https://github.com/"} target="_blank" rel="noopener noreferrer">
                        <FontAwesomeIcon icon={faGithub} className="mr-2"/>
                    </a>
                </div>
                <div className={"contact-links-email"}>
                    <a href={"javierchen22952295@gmail.com"}>
                        <FontAwesomeIcon icon={faEnvelope} className="mr-2"/>
                    </a>
                </div>
            </div>
        </div>
            <div className="mt-10"> {/* 添加一些间距以避免内容被导航栏遮挡 */}
                {children}
            </div>


        </body>
        </html>
    );
}
